[dependencies]
pip = ["pyyaml", "types-PyYAML", "demjson3"]
system = ["texlive-latex-recommended"]

[analyzer.tera]

[processor.tera]
dep_inputs = [
    "config/project.lua",
    "config/personal.lua",
]

[processor.tags]
src_dirs = ["syllabi", "out/generator"]
required_fields = ["tags", "level", "category", "audience"]
required_field_groups = [["duration_hours"], ["duration_hours_long", "duration_hours_short"]]

[processor.pandoc.syllabi]
src_dirs = ["syllabi"]
formats = ["pdf", "html", "docx"]
output_dir = "_site"
args = ["--standalone", "--embed-resources", "--css=resources/syllabus.css", "--lua-filter=resources/pandoc_filter.lua"]
dep_inputs = ["resources/syllabus.css", "resources/pandoc_filter.lua"]

[processor.pandoc.generator]
src_dirs = ["out/generator"]
formats = ["pdf", "html", "docx"]
output_dir = "_site/tracks"
args = ["--standalone", "--embed-resources", "--css=resources/syllabus.css", "--lua-filter=resources/pandoc_filter.lua"]
dep_inputs = ["resources/syllabus.css", "resources/pandoc_filter.lua"]

[processor.script]
src_dirs = ["syllabi", "out/generator"]
src_extensions = [".md"]
command = "scripts/check_md.py"
batch = true

[processor.zspell]
src_dirs = ["syllabi", "out/generator"]

[processor.terms]
terms_dir = "terms.single_meaning"
ambiguous_terms_dir = "terms.ambiguous"
src_dirs = ["syllabi", "out/generator"]

[processor.stylelint]
src_dirs = ["resources"]

[processor.htmlhint]
src_dirs = ["resources"]

[processor.eslint]
args = ["-c", "config/eslint.config.js"]
src_dirs = ["resources"]

[processor.generator]
src_dirs = ["tracks"]
src_extensions = [".yaml"]
batch = true
command = "scripts/build_tracks.py"
output_extension = "md"

[processor.explicit.build_site]
command = "scripts/build_site.py"
inputs = [
    "resources/index.html",
    "resources/index.css",
    "resources/index.js",
    "tags/level.txt",
    "tags/category.txt",
    "tags/audiences.txt",
]
input_globs = [
    "_site/courses/**/*.html",
    "_site/tracks/*.html",
]
output_dirs = ["_site"]

[processor.luacheck]
src_dirs = ["config", "resources"]

[processor.mypy]
src_dirs = ["scripts"]

[processor.ruff]
src_dirs = ["scripts"]

[processor.iyamllint]
src_dirs = ["tracks"]

[processor.ijsonlint]
src_dirs = ["."]
